/// \file
/// \addtogroup Recognizer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from recognizer.djinni

#pragma once

#include <functional>

namespace bnb { namespace interfaces {

enum class face_search_mode : int {
    fast,
    good_for_first_face,
    good,
};

} }  // namespace bnb::interfaces

namespace std {

template <>
struct hash<::bnb::interfaces::face_search_mode> {
    size_t operator()(::bnb::interfaces::face_search_mode type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
/// @}

