/// \file
/// \addtogroup Recognizer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from recognizer.djinni

#pragma once

#include <functional>

namespace bnb { namespace interfaces {

enum class feature_id : int {
    frx,
    action_units,
    background,
    hair,
    eyes,
    skin,
    face,
    face_skin,
    lips,
    lips_shine,
    occlussion,
    glasses,
    acne,
    hand_skelet,
    frame_brightness,
    eye_bags,
    face_acne,
    ruler,
    hair_strand,
    pose_estimation,
    /**
     * This feature will prepare blurred texture to apply on
     * input image resulting a smoothed skin. 
     */
    skin_smoothing,
    /**
     * This feature will prepare blurred texture to apply on
     * input image resulting a smoothed neck skin.
     */
    neck_smoothing,
    /** Body segmentation. I.e. bodies detection on the frame. */
    body,
    /** Draw NN-generated smile on user face */
    creepy_smile,
};

} }  // namespace bnb::interfaces

namespace std {

template <>
struct hash<::bnb::interfaces::feature_id> {
    size_t operator()(::bnb::interfaces::feature_id type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
/// @}

