source 'https://github.com/Banuba/specs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
use_frameworks! 

target 'Example' do
  pod 'BanubaARCloudSDK', '1.26.0' #optional
  pod 'BanubaVideoEditorSDK', '1.26.0'
  pod 'BanubaAudioBrowserSDK', '1.26.0' #optional
  pod 'BanubaMusicEditorSDK', '1.26.0'
  pod 'BanubaOverlayEditorSDK', '1.26.0'
  pod 'BanubaSDKSimple', '1.26.0'
  pod 'BanubaEffectPlayer', '1.26.0'
  pod 'BanubaSDK', '1.26.0'
  pod 'BanubaSDKServicing', '1.26.0'
  pod 'VideoEditor', '1.26.0'
  pod 'BanubaUtilities', '1.26.0'
  pod 'BanubaVideoEditorGallerySDK', '1.26.0' #optional
  pod 'BanubaVideoEditorTrimSDK', '1.26.0'
  pod 'BanubaLicenseServicingSDK', '1.26.0'
  pod 'BanubaTokenStorageSDK', '1.26.0' #optional

  pod 'BNBLicenseUtils', '1.26.0'
  
  pod 'VEExportSDK', '1.26.0'
  pod 'VEEffectsSDK', '1.26.0'
  pod 'VEPlaybackSDK', '1.26.0'
  
  
  pod 'lottie-ios'
  pod "BSImagePicker"
  
end
