/// \file
/// \addtogroup Renderer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from renderer.djinni

#pragma once

#include "bnb/types/interfaces/frame_data.hpp"
#include <bnb/utils/defs.hpp>
#include <cstdint>
#include <memory>

namespace bnb { namespace interfaces {

/**
 * Renders debug views of all enabled features
 * Requires creation with active gl context for correct feature subrenderers' init
 */
class BNB_EXPORT debug_renderer {
public:
    virtual ~debug_renderer() {}

    /** This method may return `null` when debug renderer is unavailable */
    static std::shared_ptr<debug_renderer> create();

    /** this pixel density is relative to a real one! */
    virtual void surface_changed(int32_t width, int32_t height, float pixel_density_w, float pixel_density_h) = 0;

    virtual void draw(const std::shared_ptr<::bnb::interfaces::frame_data> & frame_data) = 0;
};

} }  // namespace bnb::interfaces
/// @}

