/// \file
/// \addtogroup Types
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#pragma once

#include <utility>
#include <vector>

namespace bnb { namespace interfaces {

/**for order of values in action units array see action_units_indices enum */
struct action_units final {
    float rot_x;
    float rot_y;
    float rot_z;
    std::vector<float> units;

    action_units(float rot_x_,
                 float rot_y_,
                 float rot_z_,
                 std::vector<float> units_)
    : rot_x(std::move(rot_x_))
    , rot_y(std::move(rot_y_))
    , rot_z(std::move(rot_z_))
    , units(std::move(units_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

