/// \file
/// \addtogroup Types
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#pragma once

#include "bnb/types/interfaces/action_units.hpp"
#include <utility>
#include <vector>

namespace bnb { namespace interfaces {

struct action_units_data final {
    std::vector<action_units> faces;

    action_units_data(std::vector<action_units> faces_)
    : faces(std::move(faces_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

