/// \file
/// \addtogroup Types
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#pragma once

#include <cstdint>
#include <utility>
#include <vector>

namespace bnb { namespace interfaces {

/** Results from depth camera */
struct depth_map final {
    std::vector<uint8_t> depth_data;
    int32_t depth_map_width;
    int32_t depth_map_height;

    depth_map(std::vector<uint8_t> depth_data_,
              int32_t depth_map_width_,
              int32_t depth_map_height_)
    : depth_data(std::move(depth_data_))
    , depth_map_width(std::move(depth_map_width_))
    , depth_map_height(std::move(depth_map_height_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

