/// \file
/// \addtogroup Types
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#pragma once

#include <utility>
#include <vector>

namespace bnb { namespace interfaces {

/** Holds recognition result from an external source (ARKit, ARCore, etc.) */
struct external_face_data final {
    std::vector<float> vertices;
    std::vector<float> model_mat;
    std::vector<float> view_mat;
    std::vector<float> proj_mat;

    external_face_data(std::vector<float> vertices_,
                       std::vector<float> model_mat_,
                       std::vector<float> view_mat_,
                       std::vector<float> proj_mat_)
    : vertices(std::move(vertices_))
    , model_mat(std::move(model_mat_))
    , view_mat(std::move(view_mat_))
    , proj_mat(std::move(proj_mat_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

