/// \file
/// \addtogroup Types
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#pragma once

#include <utility>

namespace bnb { namespace interfaces {

struct eyes_state final {
    bool is_open_left;
    bool is_open_right;

    eyes_state(bool is_open_left_,
               bool is_open_right_)
    : is_open_left(std::move(is_open_left_))
    , is_open_right(std::move(is_open_right_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

