/// \file
/// \addtogroup Types
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#pragma once

#include "bnb/types/interfaces/transformed_mask_byte.hpp"
#include <utility>

namespace bnb { namespace interfaces {

struct lips_shine_mask final {
    /**shine_mask */
    transformed_mask_byte meta;
    /**blending coeffcient */
    float v_min;
    float v_max;

    lips_shine_mask(transformed_mask_byte meta_,
                    float v_min_,
                    float v_max_)
    : meta(std::move(meta_))
    , v_min(std::move(v_min_))
    , v_max(std::move(v_max_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

