/// \file
/// \addtogroup Types
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#pragma once

#include <functional>

namespace bnb { namespace interfaces {

enum class pixel_format : int {
    rgb,
    rgba,
    bgr,
    bgra,
    argb,
};

} }  // namespace bnb::interfaces

namespace std {

template <>
struct hash<::bnb::interfaces::pixel_format> {
    size_t operator()(::bnb::interfaces::pixel_format type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
/// @}

