/// \file
/// \addtogroup Types
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#pragma once

#include <utility>

namespace bnb { namespace interfaces {

struct point2d final {
    float x;
    float y;

    point2d(float x_,
            float y_)
    : x(std::move(x_))
    , y(std::move(y_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

