/// \file
/// \addtogroup Types
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#pragma once

#include <functional>

namespace bnb { namespace interfaces {

enum class rotation : int {
    deg_0,
    deg_90,
    deg_180,
    deg_270,
};

} }  // namespace bnb::interfaces

namespace std {

template <>
struct hash<::bnb::interfaces::rotation> {
    size_t operator()(::bnb::interfaces::rotation type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
/// @}

