/// \file
/// \addtogroup Types
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#pragma once

#include "bnb/types/interfaces/transformed_mask.hpp"
#include <cstdint>
#include <utility>
#include <vector>

namespace bnb { namespace interfaces {

struct transformed_mask_byte final {
    transformed_mask meta;
    std::vector<int8_t> mask;

    transformed_mask_byte(transformed_mask meta_,
                          std::vector<int8_t> mask_)
    : meta(std::move(meta_))
    , mask(std::move(mask_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

