#pragma once

#include <bnb/effect_player/interfaces/analytics_config.hpp>
#include <bnb/effect_player/interfaces/analytics_listener.hpp>
#include <bnb/effect_player/interfaces/camera_orientation.hpp>
#include <bnb/effect_player/interfaces/camera_poi_listener.hpp>
#include <bnb/effect_player/interfaces/consistency_mode.hpp>
#include <bnb/effect_player/interfaces/debug_interface.hpp>
#include <bnb/effect_player/interfaces/effect.hpp>
#include <bnb/effect_player/interfaces/effect_event_listener.hpp>
#include <bnb/effect_player/interfaces/effect_manager.hpp>
#include <bnb/effect_player/interfaces/effect_player.hpp>
#include <bnb/effect_player/interfaces/effect_player_configuration.hpp>
#include <bnb/effect_player/interfaces/effect_player_playback_state.hpp>
#include <bnb/effect_player/interfaces/effect_status.hpp>
#include <bnb/effect_player/interfaces/error_listener.hpp>
#include <bnb/effect_player/interfaces/face_number_listener.hpp>
#include <bnb/effect_player/interfaces/frame_duration_listener.hpp>
#include <bnb/effect_player/interfaces/hint_listener.hpp>
#include <bnb/effect_player/interfaces/input_manager.hpp>
#include <bnb/effect_player/interfaces/low_light_listener.hpp>
#include <bnb/effect_player/interfaces/nn_mode.hpp>
#include <bnb/effect_player/interfaces/process_image_params.hpp>
#include <bnb/effect_player/interfaces/push_frame_mocker.hpp>
#include <bnb/effect_player/interfaces/touch.hpp>
#include <bnb/effect_player/interfaces/types.hpp>
