/// \file
/// \addtogroup EffectPlayer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>

namespace bnb { namespace interfaces {

/**internal */
struct analytics_config final {
    /** Number of frames to record when face was found */
    int32_t frames_count;
    /** Number of frames to skip before record start */
    int32_t delay_for_record_with_face;
    /** Path to folder for results storing */
    std::string output_path;

    analytics_config(int32_t frames_count_,
                     int32_t delay_for_record_with_face_,
                     std::string output_path_)
    : frames_count(std::move(frames_count_))
    , delay_for_record_with_face(std::move(delay_for_record_with_face_))
    , output_path(std::move(output_path_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

