/// \file
/// \addtogroup EffectPlayer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <string>

namespace bnb { namespace interfaces {

/**internal */
class BNB_EXPORT analytics_listener {
public:
    virtual ~analytics_listener() {}

    /**internal */
    virtual void on_analytics_event(const std::string & file_path) = 0;
};

} }  // namespace bnb::interfaces
/// @}

