/// \file
/// \addtogroup EffectPlayer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#pragma once

#include <bnb/utils/defs.hpp>

namespace bnb { namespace interfaces {

/** Callback to get center of square bounding the face. */
class BNB_EXPORT camera_poi_listener {
public:
    virtual ~camera_poi_listener() {}

    /** @see EffectPlayer.setCameraPoiListener */
    virtual void on_camera_poi_changed(float x, float y) = 0;
};

} }  // namespace bnb::interfaces
/// @}

