/// \file
/// \addtogroup EffectPlayer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <cstdint>
#include <memory>
#include <string>

namespace bnb { namespace interfaces {

class effect;
class effect_event_listener;
class error_listener;
class hint_listener;

class BNB_EXPORT effect_manager {
public:
    virtual ~effect_manager() {}

    /**
     * Add callback to receive errors messages from Effect Player.
     * Thread-safe. May be called from any thread
     */
    virtual void add_error_listener(const std::shared_ptr<error_listener> & error_listener) = 0;

    /**
     * Remove callback to receive errors messages from Effect Player.
     * Thread-safe. May be called from any thread
     */
    virtual void remove_error_listener(const std::shared_ptr<error_listener> & error_listener) = 0;

    /**
     * Add callback to receive user-visible messages from effects.
     * You should display them on UI.
     * Thread-safe. May be called from any thread
     */
    virtual void add_hint_listener(const std::shared_ptr<hint_listener> & hint_listener) = 0;

    /**
     * Remove callback to receive user-visible messages from effects.
     * Thread-safe. May be called from any thread
     */
    virtual void remove_hint_listener(const std::shared_ptr<hint_listener> & hint_listener) = 0;

    /**
     * Add callback to receive events from effect.
     * Thread-safe. May be called from any thread
     */
    virtual void add_effect_event_listener(const std::shared_ptr<effect_event_listener> & effect_event_listener) = 0;

    /**
     * Remove callback to receive events from effect.
     * Thread-safe. May be called from any thread
     */
    virtual void remove_effect_event_listener(const std::shared_ptr<effect_event_listener> & effect_event_listener) = 0;

    /**
     * load and activate effect sync
     * MUST be called from the render thread
     */
    virtual std::shared_ptr<effect> load(const std::string & url) = 0;

    /**
     * load effect async, activate in the draw() call when it will be ready
     * Thread-safe. May be called from any thread
     */
    virtual std::shared_ptr<effect> load_async(const std::string & url) = 0;

    /**
     * Unload effect from cache. if no currently loading effect -
     * works the same way as load(""); launches empty effect loading.
     * MUST be called from the render thread
     */
    virtual void unload(const std::shared_ptr<effect> & effect) = 0;

    /**
     * get active
     * Thread-safe. May be called from any thread
     */
    virtual std::shared_ptr<effect> current() = 0;

    /**
     * size in Mb, effects count
     * Thread-safe. May be called from any thread
     */
    virtual void change_cache_quota(int32_t size, int32_t count) = 0;

    /**
     * Forces cache reload on the next load/load_async call
     * Thread-safe. May be called from any thread
     */
    virtual void force_cache_reload() = 0;

    /**
     * Set effect audio volume.
     * Thread-safe. May be called from any thread
     * @param volume A value in range `[0, 1]`, where `1` means maximum volume.
     */
    virtual void set_effect_volume(float volume) = 0;

    /**
     * Changes effect player render size, should be called on render thread.
     * MUST be called from the render thread
     */
    virtual void set_effect_size(int32_t fx_width, int32_t fx_height) = 0;
};

} }  // namespace bnb::interfaces
/// @}

