/// \file
/// \addtogroup EffectPlayer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#pragma once

#include <functional>

namespace bnb { namespace interfaces {

enum class effect_player_playback_state : int {
    /** Not initialized/stopped states */
    inactive,
    /** Active playback state */
    active,
    /** Playback is paused and ready to resume from saved position */
    paused,
};

} }  // namespace bnb::interfaces

namespace std {

template <>
struct hash<::bnb::interfaces::effect_player_playback_state> {
    size_t operator()(::bnb::interfaces::effect_player_playback_state type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
/// @}

