/// \file
/// \addtogroup EffectPlayer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <string>

namespace bnb { namespace interfaces {

/**
 * Interface to receive errors from `EffectPlayer`.
 * Could be called from any thread inside EffectPlayer. So the implementation of this listener should be thread-safe.
 */
class BNB_EXPORT error_listener {
public:
    virtual ~error_listener() {}

    /** @param domain source of error (e.g. "js_engine") */
    virtual void on_error(const std::string & domain, const std::string & message) = 0;
};

} }  // namespace bnb::interfaces
/// @}

