/// \file
/// \addtogroup EffectPlayer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <cstdint>

namespace bnb { namespace interfaces {

/** Callback to get face number detected. */
class BNB_EXPORT face_number_listener {
public:
    virtual ~face_number_listener() {}

    /** Will be called only when amount of found faces changes. */
    virtual void on_face_number_changed(int32_t face_number) = 0;
};

} }  // namespace bnb::interfaces
/// @}

