/// \file
/// \addtogroup EffectPlayer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#pragma once

#include <bnb/utils/defs.hpp>

namespace bnb { namespace interfaces {

/** Callback interface to receive FPS timings. */
class BNB_EXPORT frame_duration_listener {
public:
    virtual ~frame_duration_listener() {}

    /** FPS information about recognition engine. */
    virtual void on_recognizer_frame_duration_changed(float instant, float averaged) = 0;

    /**
     * FPS information about camera images push.
     * @see EffectPlayer.pushFrame
     */
    virtual void on_camera_frame_duration_changed(float instant, float averaged) = 0;

    /** FPS of Effect Player drawing. */
    virtual void on_render_frame_duration_changed(float instant, float averaged) = 0;
};

} }  // namespace bnb::interfaces
/// @}

