/// \file
/// \addtogroup EffectPlayer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <string>

namespace bnb { namespace interfaces {

/**
 * Callback to receive "hints" (e.g. "Open mouth" from effect).
 * Display them on UI.
 */
class BNB_EXPORT hint_listener {
public:
    virtual ~hint_listener() {}

    virtual void on_hint(const std::string & hint_message) = 0;
};

} }  // namespace bnb::interfaces
/// @}

