/// \file
/// \addtogroup EffectPlayer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#pragma once

#include <bnb/utils/defs.hpp>

namespace bnb { namespace interfaces {

/**internal */
class BNB_EXPORT low_light_listener {
public:
    virtual ~low_light_listener() {}

    /**internal */
    virtual void on_low_light_changed(bool is_low_light) = 0;
};

} }  // namespace bnb::interfaces
/// @}

