/// \file
/// \addtogroup EffectPlayer
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#pragma once

#include "bnb/types/interfaces/pixel_rect.hpp"
#include <optional>
#include <string>
#include <utility>
#include <vector>

namespace bnb { namespace interfaces {

struct process_image_params final {
    /** Set this param to force running of acne processing feature */
    bool acne_processing;
    /** User-defined acne areas to mask, rectangles are in input image coordinate space */
    std::optional<std::vector<::bnb::interfaces::pixel_rect>> acne_user_areas;
    /** For internal use, not for clients. Stores path to JSON with face data, to mock frx results */
    std::optional<std::string> face_data_json_path;

    process_image_params(bool acne_processing_,
                         std::optional<std::vector<::bnb::interfaces::pixel_rect>> acne_user_areas_,
                         std::optional<std::string> face_data_json_path_)
    : acne_processing(std::move(acne_processing_))
    , acne_user_areas(std::move(acne_user_areas_))
    , face_data_json_path(std::move(face_data_json_path_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

