/// \file
/// \addtogroup Spal
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from spal.djinni

#pragma once

#include <bnb/types/full_image.hpp>
#include <bnb/utils/defs.hpp>
#include <memory>
#include <optional>
#include <string>
#include <unordered_map>

namespace bnb { namespace interfaces {

class BNB_EXPORT frames_provider {
public:
    virtual ~frames_provider() {}

    static std::shared_ptr<frames_provider> create(const std::string & path);

    /** @return `null` if there is no more frames. */
    virtual std::optional<::bnb::full_image_t> next_image() = 0;

    virtual std::unordered_map<std::string, std::string> get_device_info() const = 0;
};

} }  // namespace bnb::interfaces
/// @}

