/// \file
/// \addtogroup Utils
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#pragma once

#include <functional>

namespace bnb { namespace interfaces {

enum class hardware_class : int {
    low,
    medium,
    high,
};

} }  // namespace bnb::interfaces

namespace std {

template <>
struct hash<::bnb::interfaces::hardware_class> {
    size_t operator()(::bnb::interfaces::hardware_class type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
/// @}

