// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>


/**internal */
@protocol BNBAnalyticsListener

/**internal */
- (void)onAnalyticsEvent:(nonnull NSString *)filePath;

@end
