// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#import <Foundation/Foundation.h>

/**for order of values in action units array see action_units_indices enum */
@interface BNBActionUnits : NSObject
- (nonnull instancetype)initWithRotX:(float)rotX
                                rotY:(float)rotY
                                rotZ:(float)rotZ
                               units:(nonnull NSArray<NSNumber *> *)units;
+ (nonnull instancetype)actionUnitsWithRotX:(float)rotX
                                       rotY:(float)rotY
                                       rotZ:(float)rotZ
                                      units:(nonnull NSArray<NSNumber *> *)units;

@property (nonatomic, readonly) float rotX;

@property (nonatomic, readonly) float rotY;

@property (nonatomic, readonly) float rotZ;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * units;

@end
