// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>

/**internal */
@interface BNBAnalyticsConfig : NSObject
- (nonnull instancetype)initWithFramesCount:(int32_t)framesCount
                     delayForRecordWithFace:(int32_t)delayForRecordWithFace
                                 outputPath:(nonnull NSString *)outputPath;
+ (nonnull instancetype)analyticsConfigWithFramesCount:(int32_t)framesCount
                                delayForRecordWithFace:(int32_t)delayForRecordWithFace
                                            outputPath:(nonnull NSString *)outputPath;

/** Number of frames to record when face was found */
@property (nonatomic, readonly) int32_t framesCount;

/** Number of frames to skip before record start */
@property (nonatomic, readonly) int32_t delayForRecordWithFace;

/** Path to folder for results storing */
@property (nonatomic, readonly, nonnull) NSString * outputPath;

@end
