// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import "BNBAttachmentType.h"
#import "BNBVec3.h"
#import <Foundation/Foundation.h>


@interface BNBAttachment : NSObject

- (BNBAttachmentType)getAttachmentType;

- (void)setClearColor:(nonnull BNBVec3 *)color;

- (nonnull BNBVec3 *)getClearColor;

@end
