// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBActionUnitsIndices)
{
    /**0 */
    BNBActionUnitsIndicesBrowDownLeft,
    BNBActionUnitsIndicesBrowDownRight,
    BNBActionUnitsIndicesBrowInnerUp,
    BNBActionUnitsIndicesBrowOuterUpLeft,
    BNBActionUnitsIndicesBrowOuterUpRight,
    BNBActionUnitsIndicesCheekPuff,
    BNBActionUnitsIndicesCheekSquintLeft,
    BNBActionUnitsIndicesCheekSquintRight,
    BNBActionUnitsIndicesJawForward,
    /**9 */
    BNBActionUnitsIndicesJawLeft,
    BNBActionUnitsIndicesJawRight,
    BNBActionUnitsIndicesJawOpen,
    BNBActionUnitsIndicesMouthClose,
    BNBActionUnitsIndicesMouthFunnel,
    BNBActionUnitsIndicesMouthPucker,
    BNBActionUnitsIndicesMouthLeft,
    BNBActionUnitsIndicesMouthRight,
    BNBActionUnitsIndicesMouthSmileLeft,
    BNBActionUnitsIndicesMouthSmileRight,
    /**19 */
    BNBActionUnitsIndicesMouthDimpleLeft,
    BNBActionUnitsIndicesMouthDimpleRight,
    BNBActionUnitsIndicesMouthRollUpper,
    BNBActionUnitsIndicesMouthShrugUpper,
    BNBActionUnitsIndicesMouthShrugLower,
    BNBActionUnitsIndicesMouthRollLower,
    BNBActionUnitsIndicesMouthFrownLeft,
    BNBActionUnitsIndicesMouthFrownRight,
    BNBActionUnitsIndicesMouthUpperUpLeft,
    BNBActionUnitsIndicesMouthUpperUpRight,
    /**29 */
    BNBActionUnitsIndicesMouthLowerDownLeft,
    BNBActionUnitsIndicesMouthLowerDownRight,
    BNBActionUnitsIndicesNoseSneerLeft,
    BNBActionUnitsIndicesNoseSneerRight,
    BNBActionUnitsIndicesMouthPressLeft,
    BNBActionUnitsIndicesMouthPressRight,
    BNBActionUnitsIndicesMouthStretchLeft,
    BNBActionUnitsIndicesMouthStretchRight,
    BNBActionUnitsIndicesEyeBlinkLeft,
    BNBActionUnitsIndicesEyeBlinkRight,
    /**39 */
    BNBActionUnitsIndicesEyeWideLeft,
    BNBActionUnitsIndicesEyeWideRight,
    BNBActionUnitsIndicesEyeSquintLeft,
    BNBActionUnitsIndicesEyeSquintRight,
    BNBActionUnitsIndicesEyeLookDownLeft,
    BNBActionUnitsIndicesEyeLookInLeft,
    BNBActionUnitsIndicesEyeLookOutLeft,
    BNBActionUnitsIndicesEyeLookUpLeft,
    BNBActionUnitsIndicesEyeLookDownRight,
    BNBActionUnitsIndicesEyeLookInRight,
    BNBActionUnitsIndicesEyeLookOutRight,
    /**50 */
    BNBActionUnitsIndicesEyeLookUpRight,
    /**51 */
    BNBActionUnitsIndicesTotalAuCount,
};
