// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import "BNBAttachmentType.h"
#import "BNBImageType.h"
#import <Foundation/Foundation.h>
@class BNBImage;
@class BNBMaterial;
@class BNBMesh;
@class BNBRenderTarget;


@interface BNBAssetManager : NSObject

- (nullable BNBImage *)createAttachment:(nonnull NSString *)name
                                   type:(BNBAttachmentType)type;

- (nullable BNBImage *)createCubemap:(nonnull NSString *)name;

- (nullable BNBRenderTarget *)createRenderTarget:(nonnull NSString *)name;

- (nullable BNBImage *)loadImage:(nonnull NSString *)name
                            type:(BNBImageType)type;

- (nullable BNBMaterial *)loadMaterial:(nonnull NSString *)fileName;

- (nullable BNBMesh *)loadMesh:(nonnull NSString *)fileName;

- (nullable BNBImage *)findImage:(nonnull NSString *)name;

@end
