// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#import <Foundation/Foundation.h>

@interface BNBCameraPosition : NSObject
- (nonnull instancetype)initWithHasCameraPosition:(int32_t)hasCameraPosition
                                         frustumL:(float)frustumL
                                         frustumR:(float)frustumR
                                         frustumT:(float)frustumT
                                         frustumB:(float)frustumB
                                         frustumN:(float)frustumN
                                         frustumF:(float)frustumF
                                          modelRX:(float)modelRX
                                          modelRY:(float)modelRY
                                          modelRZ:(float)modelRZ
                                          modelTX:(float)modelTX
                                          modelTY:(float)modelTY
                                          modelTZ:(float)modelTZ
                                      headCenterX:(float)headCenterX
                                      headCenterY:(float)headCenterY
                                       modelViewM:(nonnull NSArray<NSNumber *> *)modelViewM
                                      projectionM:(nonnull NSArray<NSNumber *> *)projectionM;
+ (nonnull instancetype)cameraPositionWithHasCameraPosition:(int32_t)hasCameraPosition
                                                   frustumL:(float)frustumL
                                                   frustumR:(float)frustumR
                                                   frustumT:(float)frustumT
                                                   frustumB:(float)frustumB
                                                   frustumN:(float)frustumN
                                                   frustumF:(float)frustumF
                                                    modelRX:(float)modelRX
                                                    modelRY:(float)modelRY
                                                    modelRZ:(float)modelRZ
                                                    modelTX:(float)modelTX
                                                    modelTY:(float)modelTY
                                                    modelTZ:(float)modelTZ
                                                headCenterX:(float)headCenterX
                                                headCenterY:(float)headCenterY
                                                 modelViewM:(nonnull NSArray<NSNumber *> *)modelViewM
                                                projectionM:(nonnull NSArray<NSNumber *> *)projectionM;

@property (nonatomic, readonly) int32_t hasCameraPosition;

@property (nonatomic, readonly) float frustumL;

@property (nonatomic, readonly) float frustumR;

@property (nonatomic, readonly) float frustumT;

@property (nonatomic, readonly) float frustumB;

@property (nonatomic, readonly) float frustumN;

@property (nonatomic, readonly) float frustumF;

@property (nonatomic, readonly) float modelRX;

@property (nonatomic, readonly) float modelRY;

@property (nonatomic, readonly) float modelRZ;

@property (nonatomic, readonly) float modelTX;

@property (nonatomic, readonly) float modelTY;

@property (nonatomic, readonly) float modelTZ;

@property (nonatomic, readonly) float headCenterX;

@property (nonatomic, readonly) float headCenterY;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * modelViewM;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * projectionM;

@end
