// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import "BNBCameraParameters.h"
#import <Foundation/Foundation.h>


@interface BNBCamera : NSObject

- (void)setActive:(BOOL)active;

- (BOOL)isActive;

- (void)setParameters:(nonnull BNBCameraParameters *)parameters;

- (nonnull BNBCameraParameters *)getParameters;

@end
