// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from celebrity_match.djinni

#import <Foundation/Foundation.h>

@interface BNBCelebrityMatchIndex : NSObject
- (nonnull instancetype)initWithIdx:(int64_t)idx
                               flip:(BOOL)flip;
+ (nonnull instancetype)celebrityMatchIndexWithIdx:(int64_t)idx
                                              flip:(BOOL)flip;

@property (nonatomic, readonly) int64_t idx;

@property (nonatomic, readonly) BOOL flip;

@end
