// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBComponentType)
{
    BNBComponentTypeCamera,
    BNBComponentTypeFaceTracker,
    BNBComponentTypeTransformation,
    BNBComponentTypeMeshInstance,
    BNBComponentTypeFaceMorphing,
};
