// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import "BNBComponentType.h"
#import <Foundation/Foundation.h>
@class BNBCamera;
@class BNBComponent;
@class BNBFaceMorphing;
@class BNBFaceTracker;
@class BNBMeshInstance;
@class BNBTransformation3d;


@interface BNBComponent : NSObject

+ (nullable BNBComponent *)create:(BNBComponentType)type;

- (BNBComponentType)getComponentType;

- (nullable BNBCamera *)asCamera;

- (nullable BNBFaceTracker *)asFaceTracker;

- (nullable BNBMeshInstance *)asMeshInstance;

- (nullable BNBFaceMorphing *)asFaceMorphing;

- (nullable BNBTransformation3d *)asTransformation;

@end
