// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from celebrity_match.djinni

#import <Foundation/Foundation.h>

/** Tuple with celebrity_match output. Four images which should have the same size as the input image. */
@interface BNBCelebrityMatchOutput : NSObject
- (nonnull instancetype)initWithName:(nonnull NSString *)name
                               width:(int32_t)width
                              height:(int32_t)height
                            channels:(int32_t)channels
                              images:(nonnull NSArray<NSData *> *)images;
+ (nonnull instancetype)celebrityMatchOutputWithName:(nonnull NSString *)name
                                               width:(int32_t)width
                                              height:(int32_t)height
                                            channels:(int32_t)channels
                                              images:(nonnull NSArray<NSData *> *)images;

@property (nonatomic, readonly, nonnull) NSString * name;

@property (nonatomic, readonly) int32_t width;

@property (nonatomic, readonly) int32_t height;

@property (nonatomic, readonly) int32_t channels;

@property (nonatomic, readonly, nonnull) NSArray<NSData *> * images;

@end
