// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>


@interface BNBCubemap : NSObject

- (void)setFaces:(nonnull NSString *)xPositive
       xNegative:(nonnull NSString *)xNegative
       yPositive:(nonnull NSString *)yPositive
       yNegative:(nonnull NSString *)yNegative
       zPositive:(nonnull NSString *)zPositive
       zNegative:(nonnull NSString *)zNegative;

- (void)loadKtx:(nonnull NSString *)filename;

- (nonnull NSString *)getXPositive;

- (nonnull NSString *)getXNegative;

- (nonnull NSString *)getYPositive;

- (nonnull NSString *)getYNegative;

- (nonnull NSString *)getZPositive;

- (nonnull NSString *)getZNegative;

@end
