// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from celebrity_match.djinni

#import "BNBCelebrityMatchBackendData.h"
#import "BNBCelebrityMatchIndex.h"
#import "BNBCelebrityMatchOutput.h"
#import "BanubaEffectPlayer/BNBFullImageData.h"
#import <Foundation/Foundation.h>
@class BNBCelebrityMatch;


@interface BNBCelebrityMatch : NSObject

+ (nullable BNBCelebrityMatch *)create:(nonnull NSString *)imageIndexPath;

/** return null optional when error */
- (nonnull NSArray<BNBCelebrityMatchIndex *> *)processPhoto:(nonnull BNBFullImageData *)inputImage;

/** return null optional when error */
- (nullable BNBCelebrityMatchOutput *)blend:(nonnull BNBCelebrityMatchIndex *)index
                                       data:(nonnull BNBCelebrityMatchBackendData *)data
                                blendCoeffs:(nonnull NSArray<NSNumber *> *)blendCoeffs;

@end
