// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>


/** Callback to get center of square bounding the face. */
@protocol BNBCameraPoiListener

/** @see EffectPlayer.setCameraPoiListener */
- (void)onCameraPoiChanged:(float)x
                         y:(float)y;

@end
