// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from celebrity_match.djinni

#import <Foundation/Foundation.h>

@interface BNBCelebrityMatchBackendData : NSObject
- (nonnull instancetype)initWithImage:(nonnull NSData *)image
                                 json:(nonnull NSString *)json;
+ (nonnull instancetype)celebrityMatchBackendDataWithImage:(nonnull NSData *)image
                                                      json:(nonnull NSString *)json;

@property (nonatomic, readonly, nonnull) NSData * image;

@property (nonatomic, readonly, nonnull) NSString * json;

@end
