// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>


@interface BNBEffect : NSObject

/** Thread-safe. May be called from any thread */
- (nonnull NSString *)url;

/**
 * Adds js method call to call queue. Queue is performed during the *draw* operation.
 * If there is an effect in loading state, all calls will be performed
 * when the effect loading is finished.
 * Thread-safe. May be called from any thread
 * @param methodName JS global function name. Member functions are not supported.
 * @param params Function arguments as JSON string.
 */
- (void)callJsMethod:(nonnull NSString *)methodName
              params:(nonnull NSString *)params;

/**
 * reset effect state
 * MUST be called from the render thread
 */
- (void)reset;

@end
