// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#import "BNBFaceSearchMode.h"
#import "BNBNnMode.h"
#import <Foundation/Foundation.h>

/** Configuration for EffectPlayer */
@interface BNBEffectPlayerConfiguration : NSObject
- (nonnull instancetype)initWithFxWidth:(int32_t)fxWidth
                               fxHeight:(int32_t)fxHeight
                               nnEnable:(BNBNnMode)nnEnable
                             faceSearch:(BNBFaceSearchMode)faceSearch
                       jsDebuggerEnable:(BOOL)jsDebuggerEnable
                            manualAudio:(BOOL)manualAudio;
+ (nonnull instancetype)effectPlayerConfigurationWithFxWidth:(int32_t)fxWidth
                                                    fxHeight:(int32_t)fxHeight
                                                    nnEnable:(BNBNnMode)nnEnable
                                                  faceSearch:(BNBFaceSearchMode)faceSearch
                                            jsDebuggerEnable:(BOOL)jsDebuggerEnable
                                                 manualAudio:(BOOL)manualAudio;

/** Width of effect rendering area */
@property (nonatomic, readonly) int32_t fxWidth;

/** Height of effect rendering area */
@property (nonatomic, readonly) int32_t fxHeight;

/** Neural Networks enabling mode */
@property (nonatomic, readonly) BNBNnMode nnEnable;

/** This setting is used for real time only. Mode is always "good" for photo and video */
@property (nonatomic, readonly) BNBFaceSearchMode faceSearch;

@property (nonatomic, readonly) BOOL jsDebuggerEnable;

/** Init audio device. Works only on iOs */
@property (nonatomic, readonly) BOOL manualAudio;

@end
