// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>


/** Callback interface for effect events. */
@protocol BNBEffectEventListener

/**
 * Callback function for custom effect events.
 * Function that is to be invoked by effect on certain events (e.g. analytics).
 *
 * @note The function is executed in Render thread.
 *
 * @param name event name
 * @param params map of (string, string) which describes events parameters (key-value pairs)
 */
- (void)onEffectEvent:(nonnull NSString *)name
               params:(nonnull NSDictionary<NSString *, NSString *> *)params;

@end
