// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#import <Foundation/Foundation.h>

@interface BNBEyesState : NSObject
- (nonnull instancetype)initWithIsOpenLeft:(BOOL)isOpenLeft
                               isOpenRight:(BOOL)isOpenRight;
+ (nonnull instancetype)eyesStateWithIsOpenLeft:(BOOL)isOpenLeft
                                    isOpenRight:(BOOL)isOpenRight;

@property (nonatomic, readonly) BOOL isOpenLeft;

@property (nonatomic, readonly) BOOL isOpenRight;

@end
