// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#import <Foundation/Foundation.h>

/** Holds recognition result from an external source (ARKit, ARCore, etc.) */
@interface BNBExternalFaceData : NSObject
- (nonnull instancetype)initWithVertices:(nonnull NSArray<NSNumber *> *)vertices
                                modelMat:(nonnull NSArray<NSNumber *> *)modelMat
                                 viewMat:(nonnull NSArray<NSNumber *> *)viewMat
                                 projMat:(nonnull NSArray<NSNumber *> *)projMat;
+ (nonnull instancetype)externalFaceDataWithVertices:(nonnull NSArray<NSNumber *> *)vertices
                                            modelMat:(nonnull NSArray<NSNumber *> *)modelMat
                                             viewMat:(nonnull NSArray<NSNumber *> *)viewMat
                                             projMat:(nonnull NSArray<NSNumber *> *)projMat;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * vertices;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * modelMat;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * viewMat;

@property (nonatomic, readonly, nonnull) NSArray<NSNumber *> * projMat;

@end
