// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>


/**
 * Interface to receive errors from `EffectPlayer`.
 * Could be called from any thread inside EffectPlayer. So the implementation of this listener should be thread-safe.
 */
@protocol BNBErrorListener

/** @param domain source of error (e.g. "js_engine") */
- (void)onError:(nonnull NSString *)domain
        message:(nonnull NSString *)message;

@end
