// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBEffectStatus)
{
    BNBEffectStatusInactive,
    BNBEffectStatusLoading,
    BNBEffectStatusActive,
};
