// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>

/** The EffectPlayerPlaybackState enum values are available states of effect player playback life cycle */
typedef NS_ENUM(NSInteger, BNBEffectPlayerPlaybackState)
{
    /** Not initialized/stopped states */
    BNBEffectPlayerPlaybackStateInactive,
    /** Active playback state */
    BNBEffectPlayerPlaybackStateActive,
    /** Playback is paused and ready to resume from saved position */
    BNBEffectPlayerPlaybackStatePaused,
};
