// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#import "BNBTransformableEvent.h"
#import <Foundation/Foundation.h>
@class BNBFaceData;


@interface BNBFrxRecognitionResult : NSObject

- (nonnull NSArray<BNBFaceData *> *)getFaces;

- (nonnull NSArray<NSNumber *> *)getTexCoords;

- (nonnull NSArray<NSNumber *> *)getTriangles;

- (nonnull BNBTransformableEvent *)getTransform;

@end
