// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>


/** Callback to get face number detected. */
@protocol BNBFaceNumberListener

/** Will be called only when amount of found faces changes. */
- (void)onFaceNumberChanged:(int32_t)faceNumber;

@end
