// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from recognizer.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBFaceSearchMode)
{
    BNBFaceSearchModeFast,
    BNBFaceSearchModeGoodForFirstFace,
    BNBFaceSearchModeGood,
};
