// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#import "BNBAcneRegions.h"
#import "BNBActionUnitsData.h"
#import "BNBDepthMap.h"
#import "BNBExternalFaceData.h"
#import "BNBEyesState.h"
#import "BNBFaceDataSource.h"
#import "BNBLipsShineMask.h"
#import "BNBTransformedMaskByte.h"
#import "BNBTransformedMaskGpu.h"
#import "BanubaEffectPlayer/BNBFullImageData.h"
#import <Foundation/Foundation.h>
@class BNBFrameData;
@class BNBFrxRecognitionResult;


/**
 * getters throw exceptions when data are not available
 * android NNs usually output gpu masks
 */
@interface BNBFrameData : NSObject

/** Creates empty `FrameData`. Use `add*` function to fill it.  */
+ (nullable BNBFrameData *)create;

- (nonnull NSArray<NSNumber *> *)getFullImgTransform;

/** Get frx_recognition_result or null if not exists */
- (nullable BNBFrxRecognitionResult *)getFrxRecognitionResult;

- (nonnull BNBActionUnitsData *)getActionUnits;

- (nonnull BNBAcneRegions *)getAcneRegions;

- (BOOL)getIsSmile;

- (BOOL)getIsMouthOpen;

- (BOOL)getIsBrowsRaised;

- (BOOL)getIsBrowsShifted;

- (BOOL)getIsWearGlasses;

- (float)getIsMale;

- (float)getRuler;

- (nonnull BNBEyesState *)getEyesState;

- (nonnull BNBTransformedMaskByte *)getBackground;

- (nonnull BNBTransformedMaskGpu *)getBackgroundGpu;

- (nonnull BNBTransformedMaskByte *)getHair;

- (nonnull BNBTransformedMaskGpu *)getHairGpu;

- (nonnull BNBTransformedMaskByte *)getSkin;

- (nonnull BNBTransformedMaskGpu *)getSkinGpu;

- (nonnull BNBTransformedMaskByte *)getLips;

- (nonnull BNBTransformedMaskGpu *)getLipsGpu;

- (nonnull BNBTransformedMaskByte *)getOcclusion;

- (nonnull BNBTransformedMaskByte *)getBody;

- (nonnull BNBLipsShineMask *)getLipsShine;

- (void)addFullImg:(nonnull BNBFullImageData *)img;

- (void)addBackground:(nonnull BNBTransformedMaskByte *)mask;

- (void)addExternalFaceData:(BNBFaceDataSource)source
                       data:(nonnull NSArray<BNBExternalFaceData *> *)data;

- (void)addDepthMap:(nonnull BNBDepthMap *)depthMap;

- (void)addFrameNumber:(int64_t)frameNumber;

- (void)addActionUnitsData:(nonnull BNBActionUnitsData *)actionUnits;

@end
