// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from spal.djinni

#import "BanubaEffectPlayer/BNBFullImageData.h"
#import <Foundation/Foundation.h>
@class BNBFramesProvider;


@interface BNBFramesProvider : NSObject

+ (nullable BNBFramesProvider *)create:(nonnull NSString *)path;

/** @return `null` if there is no more frames. */
- (nullable BNBFullImageData *)nextImage;

- (nonnull NSDictionary<NSString *, NSString *> *)getDeviceInfo;

@end
