// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>


@interface BNBFaceTracker : NSObject

- (void)setFaceIndex:(int32_t)index;

- (int32_t)getFaceIndex;

- (BOOL)hasFace;

@end
