// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>


/**
 * Callback to receive "hints" (e.g. "Open mouth" from effect).
 * Display them on UI.
 */
@protocol BNBHintListener

- (void)onHint:(nonnull NSString *)hintMessage;

@end
