// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBHardwareClass)
{
    BNBHardwareClassLow,
    BNBHardwareClassMedium,
    BNBHardwareClassHigh,
};
