// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import "BNBImageType.h"
#import <Foundation/Foundation.h>
@class BNBAttachment;
@class BNBCubemap;
@class BNBSegmentationMask;
@class BNBTexture;
@class BNBVideo;
@class BNBWeightedLut;


@interface BNBImage : NSObject

- (nonnull NSString *)getName;

- (BNBImageType)getType;

- (nullable BNBAttachment *)asAttachment;

- (nullable BNBCubemap *)asCubemap;

- (nullable BNBSegmentationMask *)asSegmentationMask;

- (nullable BNBTexture *)asTexture;

- (nullable BNBVideo *)asVideo;

- (nullable BNBWeightedLut *)asWeightedLut;

- (void)reload;

@end
