// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#import "BNBTouch.h"
#import <Foundation/Foundation.h>


/**
 * Class to accepts touches from user.
 *
 * Key in each map is id of an event.
 */
@interface BNBInputManager : NSObject

- (void)onTouchesBegan:(nonnull NSDictionary<NSNumber *, BNBTouch *> *)tocuhes;

- (void)onTouchesMoved:(nonnull NSDictionary<NSNumber *, BNBTouch *> *)tocuhes;

- (void)onTouchesEnded:(nonnull NSDictionary<NSNumber *, BNBTouch *> *)tocuhes;

- (void)onTouchesCancelled:(nonnull NSDictionary<NSNumber *, BNBTouch *> *)tocuhes;

- (void)onRotationGesture:(float)angle;

- (void)onScaleGesture:(float)scale;

- (void)onSwipeGesture:(float)dirX
                  dirY:(float)dirY;

- (void)onDoubleTapGesture:(nonnull BNBTouch *)pos;

- (void)onLongTapGesture:(nonnull BNBTouch *)pos;

- (void)onGestureEnded:(nonnull NSString *)id;

@end
