// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>
@class BNBLayer;


@interface BNBLayer : NSObject

+ (nullable BNBLayer *)create:(nonnull NSString *)name;

- (void)setName:(nonnull NSString *)name;

- (nonnull NSString *)getName;

- (void)setActive:(BOOL)active;

- (BOOL)isActive;

- (void)enableMorphing:(BOOL)enable;

- (BOOL)isMorphingEnabled;

@end
