// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#import <Foundation/Foundation.h>


/**internal */
@protocol BNBLowLightListener

/**internal */
- (void)onLowLightChanged:(BOOL)isLowLight;

@end
