// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>


@interface BNBMesh : NSObject

- (nonnull NSString *)getName;

- (int32_t)getGeometriesNum;

- (nonnull NSArray<NSString *> *)getMaterials;

- (nonnull NSArray<NSString *> *)getAnimations;

- (void)reload;

@end
