// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from makeup_transfer.djinni

#import "BNBMakeupTransferOutput.h"
#import "BanubaEffectPlayer/BNBFullImageData.h"
#import <Foundation/Foundation.h>
@class BNBMakeupTransfer;


@interface BNBMakeupTransfer : NSObject

+ (nullable BNBMakeupTransfer *)create;

- (nullable BNBMakeupTransferOutput *)processPhoto:(nonnull BNBFullImageData *)sourceImage
                                       targetImage:(nonnull BNBFullImageData *)targetImage;

@end
