// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from makeup_transfer.djinni

#import <Foundation/Foundation.h>

/** Tuple with makeup_transfer output. */
@interface BNBMakeupTransferOutput : NSObject
- (nonnull instancetype)initWithWidth:(int32_t)width
                               height:(int32_t)height
                             channels:(int32_t)channels
                                image:(nonnull NSData *)image;
+ (nonnull instancetype)makeupTransferOutputWithWidth:(int32_t)width
                                               height:(int32_t)height
                                             channels:(int32_t)channels
                                                image:(nonnull NSData *)image;

@property (nonatomic, readonly) int32_t width;

@property (nonatomic, readonly) int32_t height;

@property (nonatomic, readonly) int32_t channels;

@property (nonatomic, readonly, nonnull) NSData * image;

@end
