// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import "BNBState.h"
#import <Foundation/Foundation.h>
@class BNBImage;
@class BNBParameter;


@interface BNBMaterial : NSObject

- (nonnull NSString *)getName;

- (void)addParameter:(nullable BNBParameter *)parameter;

- (nonnull NSArray<BNBParameter *> *)getParameters;

- (void)removeParameter:(nullable BNBParameter *)parameter;

- (void)setState:(nonnull BNBState *)state;

- (nonnull BNBState *)getState;

- (void)addImage:(nonnull NSString *)sampler
           image:(nullable BNBImage *)image;

- (nonnull NSArray<NSString *> *)getSamplers;

- (nonnull NSArray<BNBImage *> *)getImages;

- (void)reload;

@end
