// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#import "BNBFramesProvider.h"
#import <Foundation/Foundation.h>
@class BNBEffectPlayer;
@class BNBPushFrameMocker;


/** This class will mock data from default source to data from file. Used for testing and debug. */
@interface BNBPushFrameMocker : NSObject

/**
 * @param player effect player to which attach this provider.
 * @param provider provider to fetch frames from
 */
+ (nullable BNBPushFrameMocker *)create:(nullable BNBEffectPlayer *)player
                               provider:(nullable BNBFramesProvider *)provider;

/**
 * Parse file and start pushing frame to Effect player.
 * @param outputFile path to file to write processed data in internal format.
 */
- (void)process:(nonnull NSString *)outputFile;

@end
