// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from postprocess.djinni

#import <Foundation/Foundation.h>
@class BNBPostprocessStage;
@class BNBPostprocessStageTextureApplier;


/** Apply stage on texture. */
@interface BNBPostprocessStageTextureApplier : NSObject

/**
 * @param stage postprocess stage which you need to apply on passed texture.
 * @param params parameters for effect.
 * @param textureId OpenGL id of texture which contain desired texture for processing.
 */
- (void)apply:(nullable BNBPostprocessStage *)stage
       params:(nonnull NSDictionary<NSString *, NSString *> *)params
    textureId:(int32_t)textureId;

+ (nullable BNBPostprocessStageTextureApplier *)create;

@end
