// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portrait_match.djinni

#import "BNBPixelRect.h"
#import <Foundation/Foundation.h>

/** Tuple with portrait_match output. */
@interface BNBPortraitMatchOutput : NSObject
- (nonnull instancetype)initWithWidth:(int32_t)width
                               height:(int32_t)height
                             channels:(int32_t)channels
                             faceRect:(nonnull BNBPixelRect *)faceRect
                                image:(nonnull NSData *)image;
+ (nonnull instancetype)portraitMatchOutputWithWidth:(int32_t)width
                                              height:(int32_t)height
                                            channels:(int32_t)channels
                                            faceRect:(nonnull BNBPixelRect *)faceRect
                                               image:(nonnull NSData *)image;

@property (nonatomic, readonly) int32_t width;

@property (nonatomic, readonly) int32_t height;

@property (nonatomic, readonly) int32_t channels;

@property (nonatomic, readonly, nonnull) BNBPixelRect * faceRect;

@property (nonatomic, readonly, nonnull) NSData * image;

@end
