// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import "BNBVec3.h"
#import <Foundation/Foundation.h>
@class BNBParameter;


@interface BNBParameter : NSObject

+ (nullable BNBParameter *)create:(nonnull NSString *)name;

- (nonnull NSString *)getName;

- (void)setInteger:(int32_t)value;

- (int32_t)getInteger;

- (void)setReal:(float)value;

- (float)getReal;

- (void)setString:(nonnull NSString *)value;

- (nonnull NSString *)getString;

- (void)setVector3:(nonnull BNBVec3 *)value;

- (nonnull BNBVec3 *)getVector3;

@end
