// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portrait_match.djinni

#import <Foundation/Foundation.h>

@interface BNBPortraitMatchBackendData : NSObject
- (nonnull instancetype)initWithImage:(nonnull NSData *)image
                                 json:(nonnull NSString *)json;
+ (nonnull instancetype)portraitMatchBackendDataWithImage:(nonnull NSData *)image
                                                     json:(nonnull NSString *)json;

@property (nonatomic, readonly, nonnull) NSData * image;

@property (nonatomic, readonly, nonnull) NSString * json;

@end
