// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from postprocess.djinni

#import <Foundation/Foundation.h>


/**
 * Class contains OpenGL texture for color filter effect.
 * Use get_postprocess_effect_params() method to get map of params for filter.
 */
@interface BNBPostprocessLutTexture : NSObject

- (nonnull NSDictionary<NSString *, NSString *> *)getPostprocessEffectParams;

@end
