// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from portrait_match.djinni

#import <Foundation/Foundation.h>

@interface BNBPortraitMatchIndex : NSObject
- (nonnull instancetype)initWithPath:(nonnull NSString *)path
                            distance:(float)distance;
+ (nonnull instancetype)portraitMatchIndexWithPath:(nonnull NSString *)path
                                          distance:(float)distance;

@property (nonatomic, readonly, nonnull) NSString * path;

@property (nonatomic, readonly) float distance;

@end
