// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from postprocess.djinni

#import <Foundation/Foundation.h>
@class BNBPostprocessLutTexture;


/** Used to create resources for postprocess effects. */
@interface BNBPostprocessHelper : NSObject

/**
 * Load resources for color filter.
 *
 * @param pathLutTexture path to LUT image. 
 * @return postprocess_lut_texture object that uses for pass parameters to color filter.
 */
+ (nullable BNBPostprocessLutTexture *)loadColorFilterResources:(nonnull NSString *)pathLutTexture;

+ (void)loadGladFunctions:(int64_t)load;

@end
