// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#import <Foundation/Foundation.h>

@interface BNBPixelRect : NSObject
- (nonnull instancetype)initWithX:(int32_t)x
                                y:(int32_t)y
                                w:(int32_t)w
                                h:(int32_t)h;
+ (nonnull instancetype)pixelRectWithX:(int32_t)x
                                     y:(int32_t)y
                                     w:(int32_t)w
                                     h:(int32_t)h;

@property (nonatomic, readonly) int32_t x;

@property (nonatomic, readonly) int32_t y;

@property (nonatomic, readonly) int32_t w;

@property (nonatomic, readonly) int32_t h;

@end
