// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import "BNBVec3.h"
#import <Foundation/Foundation.h>
@class BNBScene;
@class BNBSceneBuilder;


@interface BNBSceneBuilder : NSObject

+ (nullable BNBSceneBuilder *)create:(nonnull NSString *)sceneName;

- (nullable BNBSceneBuilder *)appendDefaultScene;

- (nullable BNBSceneBuilder *)appendBeautyScene:(int32_t)faceNumber;

- (nullable BNBSceneBuilder *)appendFaceTrackerDebugScene:(int32_t)faceNumber
                                                    color:(nonnull BNBVec3 *)color;

- (nullable BNBSceneBuilder *)appendSpiderDebugScene:(nonnull NSString *)url
                                          faceNumber:(int32_t)faceNumber;

- (nullable BNBSceneBuilder *)appendTrollsScene:(nonnull NSString *)url;

- (nullable BNBSceneBuilder *)appendIncrediblesScene:(nonnull NSString *)url;

- (nullable BNBSceneBuilder *)appendAnimeStyleScene:(nonnull NSString *)url;

- (nullable BNBSceneBuilder *)appendTransylvaniaScene:(nonnull NSString *)url;

- (nullable BNBScene *)getResult;

@end
