// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import "BNBSegmentationMaskType.h"
#import <Foundation/Foundation.h>


@interface BNBSegmentationMask : NSObject

- (void)setMaskType:(BNBSegmentationMaskType)type;

- (BNBSegmentationMaskType)getMaskType;

- (void)setActive:(BOOL)active;

- (BOOL)isActive;

@end
