// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import "BNBBlendingMode.h"
#import <Foundation/Foundation.h>

@interface BNBState : NSObject
- (nonnull instancetype)initWithBlending:(BNBBlendingMode)blending
                                  zWrite:(BOOL)zWrite
                                   zTest:(BOOL)zTest
                              colorWrite:(BOOL)colorWrite
                               backFaces:(BOOL)backFaces;
+ (nonnull instancetype)stateWithBlending:(BNBBlendingMode)blending
                                   zWrite:(BOOL)zWrite
                                    zTest:(BOOL)zTest
                               colorWrite:(BOOL)colorWrite
                                backFaces:(BOOL)backFaces;

@property (nonatomic, readonly) BNBBlendingMode blending;

@property (nonatomic, readonly) BOOL zWrite;

@property (nonatomic, readonly) BOOL zTest;

@property (nonatomic, readonly) BOOL colorWrite;

@property (nonatomic, readonly) BOOL backFaces;

@end
