// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import "BNBVec3.h"
#import <Foundation/Foundation.h>


@interface BNBTransformation3d : NSObject

- (void)setTranslation:(nonnull BNBVec3 *)position;

- (nonnull BNBVec3 *)getTranslation;

- (void)setRotation:(nonnull BNBVec3 *)anglesDeg;

- (nonnull BNBVec3 *)getRotation;

- (void)setScale:(nonnull BNBVec3 *)factor;

- (nonnull BNBVec3 *)getScale;

@end
