// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#import "BNBPixelRect.h"
#import "BNBPoint2d.h"
#import "BNBRotation.h"
#import <Foundation/Foundation.h>
@class BNBTransformation;


@interface BNBTransformation : NSObject

/** Constructs identity transform */
+ (nullable BNBTransformation *)makeIdentity;

/** Constructs from mat_t */
+ (nullable BNBTransformation *)makeData:(nonnull NSArray<NSNumber *> *)mat;

/** Constructs rotate transformation */
+ (nullable BNBTransformation *)makeRot:(BNBRotation)rot;

/** Constructs affine transformation */
+ (nullable BNBTransformation *)makeAffine:(float)scaleX
                                    scaleY:(float)scaleY
                                        tX:(float)tX
                                        tY:(float)tY
                                       rot:(BNBRotation)rot
                                     flipX:(BOOL)flipX
                                     flipY:(BOOL)flipY;

/**
 * Constructs transformation from source to target rectangle
 * Rotation and flips are around rectangles' center
 */
+ (nullable BNBTransformation *)makeRects:(nonnull BNBPixelRect *)sourceRect
                               targetRect:(nonnull BNBPixelRect *)targetRect
                                      rot:(BNBRotation)rot
                                    flipX:(BOOL)flipX
                                    flipY:(BOOL)flipY;

/**
 * Applies transform t after this
 * e.g. {rotate >> translate;} rotates first: (initial -> rotated) >> (rotated -> translated) = (initial -> translated)
 */
- (nullable BNBTransformation *)chainRight:(nullable BNBTransformation *)t;

/** Apply transform to point */
- (nonnull BNBPoint2d *)transformPoint:(nonnull BNBPoint2d *)p;

- (nonnull BNBPixelRect *)transformRect:(nonnull BNBPixelRect *)rect;

- (BOOL)equals:(nullable BNBTransformation *)t;

/**
 * Get the inverse of the transformation
 * @throw std::logic_error when matrix is singular
 */
- (nullable BNBTransformation *)inverseJ;

/** Clone the transformation */
- (nullable BNBTransformation *)cloneJ;

/** Returns 3x3 row-maj transform matrix */
- (nonnull NSArray<NSNumber *> *)getMatJ;

@end
