// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#import "BNBHardwareClass.h"
#import "BNBSeverityLevel.h"
#import <Foundation/Foundation.h>
@protocol BNBLogRecordCallback;


@interface BNBUtilityManager : NSObject

+ (void)initialize:(nonnull NSArray<NSString *> *)resourcePaths
       clientToken:(nonnull NSString *)clientToken;

+ (void)release;

/** Diagnostic crash. Use this to check you crash analytics systems.  */
+ (void)diagnosticCrash;

/**
 * Get information about CPU capabilities. Mainly for usage on Android
 * @return JSON-string describing CPU capabilties
 */
+ (nonnull NSString *)cpuEnv;

/**
 * Check device SoC class.
 * Only Android supported now, for other platforms always return hardware_class::high
 * @return hardware class of device
 */
+ (BNBHardwareClass)getHardwareClass;

+ (void)setLogLevel:(BNBSeverityLevel)level;

/**
 * Set callback to recieve log events from Banuba SDK.
 * @param cb Callback
 * @param lvl recieve logs with specified and higher levels
 */
+ (void)setLogRecordCallback:(nullable id<BNBLogRecordCallback>)cb
                         lvl:(BNBSeverityLevel)lvl;

@end
