// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>


@interface BNBVideo : NSObject

- (void)setPosition:(int32_t)position;

- (int32_t)getPosition;

- (void)play;

- (void)pause;

- (BOOL)isPlaying;

@end
