// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>

@interface BNBVec3 : NSObject
- (nonnull instancetype)initWithX:(float)x
                                y:(float)y
                                z:(float)z;
+ (nonnull instancetype)vec3WithX:(float)x
                                y:(float)y
                                z:(float)z;

@property (nonatomic, readonly) float x;

@property (nonatomic, readonly) float y;

@property (nonatomic, readonly) float z;

@end
