// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>


@interface BNBWeightedLut : NSObject

- (void)setWeight:(float)value;

- (float)getWeight;

- (void)setFile:(nonnull NSString *)fileName;

- (nonnull NSString *)getFile;

- (void)reload;

@end
