/// \file
/// \addtogroup Postprocess
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from postprocess.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <string>
#include <unordered_map>

namespace bnb { namespace interfaces {

/**
 * Class contains OpenGL texture for color filter effect.
 * Use get_postprocess_effect_params() method to get map of params for filter.
 */
class BNB_EXPORT postprocess_lut_texture {
public:
    virtual ~postprocess_lut_texture() {}

    virtual std::unordered_map<std::string, std::string> get_postprocess_effect_params() = 0;
};

} }  // namespace bnb::interfaces
/// @}

