/// \file
/// \addtogroup Postprocess
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from postprocess.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <memory>
#include <string>

namespace bnb { namespace interfaces {

/**
 * Can be used to add additional effects.
 *
 * After applying the changes the next states:
 *   - active texture,
 *   - binding texture,
 *   - depth test,
 *   - culling face,
 *   - blend mode.
 */
class BNB_EXPORT postprocess_stage {
public:
    virtual ~postprocess_stage() {}

    /**
     * Create a postprocess stage by name. 
     * @param name name of postprocess stage you want to create.
     */
    static std::shared_ptr<postprocess_stage> create(const std::string & name);
};

} }  // namespace bnb::interfaces
/// @}

