#pragma once

#include <bnb/scene/interfaces/animation_mode.hpp>
#include <bnb/scene/interfaces/asset_manager.hpp>
#include <bnb/scene/interfaces/asset_type.hpp>
#include <bnb/scene/interfaces/attachment.hpp>
#include <bnb/scene/interfaces/attachment_type.hpp>
#include <bnb/scene/interfaces/blending_mode.hpp>
#include <bnb/scene/interfaces/camera.hpp>
#include <bnb/scene/interfaces/camera_parameters.hpp>
#include <bnb/scene/interfaces/component.hpp>
#include <bnb/scene/interfaces/component_type.hpp>
#include <bnb/scene/interfaces/cubemap.hpp>
#include <bnb/scene/interfaces/entity.hpp>
#include <bnb/scene/interfaces/face_morphing.hpp>
#include <bnb/scene/interfaces/face_tracker.hpp>
#include <bnb/scene/interfaces/image.hpp>
#include <bnb/scene/interfaces/image_type.hpp>
#include <bnb/scene/interfaces/layer.hpp>
#include <bnb/scene/interfaces/material.hpp>
#include <bnb/scene/interfaces/mesh.hpp>
#include <bnb/scene/interfaces/mesh_instance.hpp>
#include <bnb/scene/interfaces/morphing_type.hpp>
#include <bnb/scene/interfaces/parameter.hpp>
#include <bnb/scene/interfaces/projection_type.hpp>
#include <bnb/scene/interfaces/render_list.hpp>
#include <bnb/scene/interfaces/render_target.hpp>
#include <bnb/scene/interfaces/scene.hpp>
#include <bnb/scene/interfaces/scene_builder.hpp>
#include <bnb/scene/interfaces/segmentation_mask.hpp>
#include <bnb/scene/interfaces/segmentation_mask_type.hpp>
#include <bnb/scene/interfaces/state.hpp>
#include <bnb/scene/interfaces/texture.hpp>
#include <bnb/scene/interfaces/texture_filtering_mode.hpp>
#include <bnb/scene/interfaces/transformation_3d.hpp>
#include <bnb/scene/interfaces/vec3.hpp>
#include <bnb/scene/interfaces/video.hpp>
#include <bnb/scene/interfaces/weighted_lut.hpp>
#include <bnb/scene/interfaces/types.hpp>
