/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#pragma once

#include <bnb/utils/defs.hpp>

namespace bnb { namespace interfaces {

enum class attachment_type;
struct vec3;

class BNB_EXPORT attachment {
public:
    virtual ~attachment() {}

    virtual attachment_type get_attachment_type() const = 0;

    virtual void set_clear_color(const vec3 & color) = 0;

    virtual vec3 get_clear_color() const = 0;
};

} }  // namespace bnb::interfaces
/// @}

