/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#pragma once

#include "bnb/scene/interfaces/projection_type.hpp"
#include <cstdint>
#include <utility>

namespace bnb { namespace interfaces {

struct camera_parameters final {
    projection_type projection;
    float z_near;
    float z_far;
    float fov;
    int32_t frame_width;
    int32_t frame_height;

    camera_parameters(projection_type projection_,
                      float z_near_,
                      float z_far_,
                      float fov_,
                      int32_t frame_width_,
                      int32_t frame_height_)
    : projection(std::move(projection_))
    , z_near(std::move(z_near_))
    , z_far(std::move(z_far_))
    , fov(std::move(fov_))
    , frame_width(std::move(frame_width_))
    , frame_height(std::move(frame_height_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

