/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#pragma once

#include <bnb/utils/defs.hpp>

namespace bnb { namespace interfaces {

struct camera_parameters;

class BNB_EXPORT camera {
public:
    virtual ~camera() {}

    virtual void set_active(bool active) = 0;

    virtual bool is_active() const = 0;

    virtual void set_parameters(const camera_parameters & parameters) = 0;

    virtual camera_parameters get_parameters() const = 0;
};

} }  // namespace bnb::interfaces
/// @}

