/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <memory>

namespace bnb { namespace interfaces {

class camera;
class face_morphing;
class face_tracker;
class mesh_instance;
class transformation_3d;
enum class component_type;

class BNB_EXPORT component {
public:
    virtual ~component() {}

    static std::shared_ptr<component> create(component_type type);

    virtual component_type get_component_type() const = 0;

    virtual std::shared_ptr<camera> as_camera() = 0;

    virtual std::shared_ptr<face_tracker> as_face_tracker() = 0;

    virtual std::shared_ptr<mesh_instance> as_mesh_instance() = 0;

    virtual std::shared_ptr<face_morphing> as_face_morphing() = 0;

    virtual std::shared_ptr<transformation_3d> as_transformation() = 0;
};

} }  // namespace bnb::interfaces
/// @}

