/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <memory>

namespace bnb { namespace interfaces {

class mesh;
enum class morphing_type;

class BNB_EXPORT face_morphing {
public:
    virtual ~face_morphing() {}

    virtual void set_morphing_type(morphing_type type) = 0;

    virtual morphing_type get_morphing_type() const = 0;

    virtual void set_warp_mesh(const std::shared_ptr<mesh> & mesh) = 0;

    virtual std::shared_ptr<mesh> get_warp_mesh() const = 0;

    virtual void set_face_weight(float value) = 0;

    virtual float get_face_weight() const = 0;

    virtual void set_nose_weight(float value) = 0;

    virtual float get_nose_weight() const = 0;

    virtual void set_eyes_weight(float value) = 0;

    virtual float get_eyes_weight() const = 0;
};

} }  // namespace bnb::interfaces
/// @}

