/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <memory>
#include <string>

namespace bnb { namespace interfaces {

class BNB_EXPORT layer {
public:
    virtual ~layer() {}

    static std::shared_ptr<layer> create(const std::string & name);

    virtual void set_name(const std::string & name) = 0;

    virtual std::string get_name() const = 0;

    virtual void set_active(bool active) = 0;

    virtual bool is_active() const = 0;

    virtual void enable_morphing(bool enable) = 0;

    virtual bool is_morphing_enabled() const = 0;
};

} }  // namespace bnb::interfaces
/// @}

