/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <cstdint>
#include <string>
#include <vector>

namespace bnb { namespace interfaces {

class BNB_EXPORT mesh {
public:
    virtual ~mesh() {}

    virtual std::string get_name() const = 0;

    virtual int32_t get_geometries_num() const = 0;

    virtual std::vector<std::string> get_materials() const = 0;

    virtual std::vector<std::string> get_animations() const = 0;

    virtual void reload() = 0;
};

} }  // namespace bnb::interfaces
/// @}

