/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <cstdint>
#include <memory>
#include <string>

namespace bnb { namespace interfaces {

struct vec3;

class BNB_EXPORT parameter {
public:
    virtual ~parameter() {}

    static std::shared_ptr<parameter> create(const std::string & name);

    virtual std::string get_name() const = 0;

    virtual void set_integer(int32_t value) = 0;

    virtual int32_t get_integer() const = 0;

    virtual void set_real(float value) = 0;

    virtual float get_real() const = 0;

    virtual void set_string(const std::string & value) = 0;

    virtual std::string get_string() const = 0;

    virtual void set_vector3(const vec3 & value) = 0;

    virtual vec3 get_vector3() const = 0;
};

} }  // namespace bnb::interfaces
/// @}

