/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#pragma once

#include <bnb/utils/defs.hpp>

namespace bnb { namespace interfaces {

enum class segmentation_mask_type;

class BNB_EXPORT segmentation_mask {
public:
    virtual ~segmentation_mask() {}

    virtual void set_mask_type(segmentation_mask_type type) = 0;

    virtual segmentation_mask_type get_mask_type() const = 0;

    virtual void set_active(bool active) = 0;

    virtual bool is_active() = 0;
};

} }  // namespace bnb::interfaces
/// @}

