/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#pragma once

#include "bnb/scene/interfaces/blending_mode.hpp"
#include <utility>

namespace bnb { namespace interfaces {

struct state final {
    blending_mode blending;
    bool z_write;
    bool z_test;
    bool color_write;
    bool back_faces;

    state(blending_mode blending_,
          bool z_write_,
          bool z_test_,
          bool color_write_,
          bool back_faces_)
    : blending(std::move(blending_))
    , z_write(std::move(z_write_))
    , z_test(std::move(z_test_))
    , color_write(std::move(color_write_))
    , back_faces(std::move(back_faces_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

