/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#pragma once

#include <bnb/utils/defs.hpp>

namespace bnb { namespace interfaces {

struct vec3;

class BNB_EXPORT transformation_3d {
public:
    virtual ~transformation_3d() {}

    virtual void set_translation(const vec3 & position) = 0;

    virtual vec3 get_translation() const = 0;

    virtual void set_rotation(const vec3 & angles_deg) = 0;

    virtual vec3 get_rotation() const = 0;

    virtual void set_scale(const vec3 & factor) = 0;

    virtual vec3 get_scale() const = 0;
};

} }  // namespace bnb::interfaces
/// @}

