/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#pragma once

#include <utility>

namespace bnb { namespace interfaces {

struct vec3 final {
    float x;
    float y;
    float z;

    vec3(float x_,
         float y_,
         float z_)
    : x(std::move(x_))
    , y(std::move(y_))
    , z(std::move(z_))
    {}
};

} }  // namespace bnb::interfaces
/// @}

