/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <cstdint>

namespace bnb { namespace interfaces {

class BNB_EXPORT video {
public:
    virtual ~video() {}

    virtual void set_position(int32_t position) = 0;

    virtual int32_t get_position() const = 0;

    virtual void play() = 0;

    virtual void pause() = 0;

    virtual bool is_playing() const = 0;
};

} }  // namespace bnb::interfaces
/// @}

