/// \file
/// \addtogroup Scene
/// @{
///
// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#pragma once

#include <bnb/utils/defs.hpp>
#include <string>

namespace bnb { namespace interfaces {

class BNB_EXPORT weighted_lut {
public:
    virtual ~weighted_lut() {}

    virtual void set_weight(float value) = 0;

    virtual float get_weight() const = 0;

    virtual void set_file(const std::string & file_name) = 0;

    virtual std::string get_file() const = 0;

    virtual void reload() = 0;
};

} }  // namespace bnb::interfaces
/// @}

